apiVersion: apps/v1
kind: Deployment
metadata:
  name: appscrip-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appscrip
  template:
    metadata:
      labels:
        app: appscrip
    spec:
      containers:
      - name: appscrip-website
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: appscrip-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: appscrip-content
        configMap:
          name: appscrip-html