apiVersion: v1
kind: Service
metadata:
  name: appscrip-service
spec:
  type: NodePort
  selector:
    app: appscrip
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081